<?php

namespace FrontBundle\Repository;

use Doctrine\ORM\EntityRepository;
use FrontBundle\Entity\Bus;

/**
 * BusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusRepository extends EntityRepository
{
    public function getBusBySejour($id){
        $qb = $this->_em->createQueryBuilder()
            ->select ('b')
            ->from (Bus::class, 'b')
            ->where('b.sejour IN (:id)')
            ->setParameter('id', $id);


        return $qb ->getQuery()->getResult();
    }
}
