<?php

namespace FrontBundle\Repository;

/**
 * CategorieTarifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieTarifRepository extends \Doctrine\ORM\EntityRepository
{
}
