<?php

namespace FrontBundle\Repository;

/**
 * CrenauxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrenauxRepository extends \Doctrine\ORM\EntityRepository
{
}
