<?php

namespace FrontBundle\Repository;

/**
 * CritereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CritereRepository extends \Doctrine\ORM\EntityRepository
{
}
