<?php

namespace FrontBundle\Repository;

use Doctrine\ORM\EntityRepository;
use FrontBundle\Entity\JourneeSecteur;

/**
 * JourneeSecteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JourneeSecteurRepository extends EntityRepository
{
    public function getJourneesBySejour($id){
        $qb = $this->_em->createQueryBuilder()
            ->select ('j')
            ->from (JourneeSecteur::class, 'j')
            ->where('j.sejour IN (:id)')
            ->setParameter('id', $id);


        return $qb ->getQuery()->getResult();
    }
}
