<?php

namespace FrontBundle\Repository;

/**
 * JourneeSecteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JourneeSecteurRepository extends \Doctrine\ORM\EntityRepository
{
}
