<?php

namespace FrontBundle\Repository;

use Doctrine\ORM\EntityRepository;
use FrontBundle\Entity\Restriction;

/**
 * RestrictionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestrictionRepository extends EntityRepository
{
    public function getRestrictionBySejour($id){
        $qb = $this->_em->createQueryBuilder()
            ->select ('r')
            ->from (Restriction::class, 'r')
            ->where('r.sejour IN (:id)')
            ->setParameter('id', $id);


        return $qb ->getQuery()->getResult();
    }
}
