<?php

namespace FrontBundle\Repository;

/**
 * TrancheQuotientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrancheQuotientRepository extends \Doctrine\ORM\EntityRepository
{
}
