<?php

namespace FrontBundle\Repository;

/**
 * VillePartenaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VillePartenaireRepository extends \Doctrine\ORM\EntityRepository
{
}
